version: '2'
volumes:
    resin-data:
services:
    baletheus:
        build: ./baletheus
        labels:
            io.balena.features.balena-api: '1'
        volumes:
            - 'resin-data:/app/data'
    prometheus:
        build: ./prometheus
        network_mode: 'host'
        volumes:
            - 'resin-data:/app/data'
    grafana:
        build: ./grafana
        network_mode: 'host'
        environment:
            - 'GF_SERVER_HTTP_PORT=80'
