global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: balena
    file_sd_configs:
        - files:
            - /app/data/balena.json
